### ISSUE TITLE
OutOfMemoryError: Java heap space 

### ISSUE THREAD

**Issue by lbyzx123** [miachm/SODS#12]
version:1.1.1

Memory overflow when reading 500 records. Stack info:

Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.github.miachm.sods.Sheet.insertRowsBefore(Sheet.java:321)
	at com.github.miachm.sods.Sheet.insertRowsAfter(Sheet.java:333)
	at com.github.miachm.sods.Sheet.appendRows(Sheet.java:51)
	at com.github.miachm.sods.Sheet.appendRow(Sheet.java:43)
	at com.github.miachm.sods.OdsReader.processTable(OdsReader.java:256)
	at com.github.miachm.sods.OdsReader.processSpreadsheet(OdsReader.java:205)
	at com.github.miachm.sods.OdsReader.iterateFilesEntries(OdsReader.java:198)
	at com.github.miachm.sods.OdsReader.processContent(OdsReader.java:77)
	at com.github.miachm.sods.OdsReader.load(OdsReader.java:43)
	at com.github.miachm.sods.OdsReader.load(OdsReader.java:35)
	at com.github.miachm.sods.SpreadSheet.<init>(SpreadSheet.java:52)
	at com.github.miachm.sods.SpreadSheet.<init>(SpreadSheet.java:39)
	at com.center.module.transfer.util.ODSParserUtils.getSpreadSheet(ODSParserUtils.java:82)

**Comment by lbyzx123** [comment]
I have an ODS file with two worksheets in it. The first one has 40 records and the second one has 360 records. When I read it, I report an oom memory error

**Comment by lbyzx123** [comment]
-Xms500m -Xmx500m

**Comment by lbyzx123** [comment]
-Xms500m -Xmx500m

**Comment by miachm** [comment]
Thanks for your report, how many columns does it have each record?

**Comment by lbyzx123** [comment]
The first sheet has 20 columns, the second sheet has 4 columns, and the third sheet has a table for instructions

**Comment by lbyzx123** [comment]
When the memory is 700m, there is no problem in parsing the worksheet, but it is very slow

**Comment by lbyzx123** [comment]
The reason may be that the third sheet has a table that merges multiple cells and enters some instructions.When I delete the third sheet, it works

**Comment by miachm** [comment]
Can you anonymize the file and upload here?

**Comment by lbyzx123** [comment]
My file download link is: https://github.com/lbyzx123/sods/blob/master/test.ods

**Comment by miachm** [comment]
The reason is this guy:
`<table:table-column table:style-name="co14" table:number-columns-repeated="16366" table:default-cell-style-name="ce1"/>
`
The SpreadSheet has defined 16366 columns **for each** sheet. Although it's only using a few ones, that's really weird.

So, the library is trying to load 16366*100 (first sheet) + 16366*500 (second sheet) + 16366 *  20 (third sheet) = 10 million of registers.

That's gonna take 400-500 MB at least. If you delete the third sheet, you are reducing the numbers of registers significantly (~400.000 registers). That's the reason why it works with -Xms500m -Xmx500m

--------

Checking the metadata, it seems than file was generated by Microsoft Excel. So i guess Microsoft Excel generates files this way by some strange reason.

if you are able to generate a template using LibreOffice, i would recommend so.

I am thinking possible workarounds, for example don't try to map blank cells in the memory.

**Comment by lbyzx123** [comment]
> The reason is this guy:
> `<table:table-column table:style-name="co14" table:number-columns-repeated="16366" table:default-cell-style-name="ce1"/> `
> The SpreadSheet has defined 16366 columns **for each** sheet. Although it's only using a few ones, that's really weird.
> 
> So, the library is trying to load:
> 
> 16366 x 100 rows (first sheet) + 16366 x 500 rows (second sheet) + 16366 x 20 rows (third sheet) = 10 million of registers.
> 
> That's gonna take 400MB at least. If you delete the third sheet, you are reducing the numbers of registers significantly (~400.000 registers) and then it can works in your available memory.
> 
> Checking the metadata, it seems than file was generated by Microsoft Excel. So i guess Microsoft Excel generates files this way by some strange reason.
> 
> if you are able to generate a template using LibreOffice, i would recommend so.
> 
> I am thinking possible workarounds, for example don't try to map blank cells in the memory.

Thank you very much! I use Microsoft's EXECL to generate templates, and our users use EXECL to fill in data. According to your suggestion, I use libreoffice to generate templates and try it.

**Comment by lbyzx123** [comment]
Can we read numcolumns as the actual number of columns? I'm sure that excel 2010 has 16384 columns, libreoffice has 64 columns, but only 20 columns are useful for our template. Is there any way to read only useful data? Our users only use Excel. Please tell us how to read only the columns defined by the template.Thanks!

**Comment by miachm** [comment]
I'm working in a patch to solve this problem, i have different options on the table. I'll update when it's fixed

> Can we read numcolumns as the actual number of columns?

New methods will be added to differentiate "sheet's dimensions" and "sheet's data".

Probably something like:

```
sheet.getContentRange(); // get a range which contains all the not-empty data of the sheet
sheet.getLastColumn(); // get the last column with data in the sheet
sheet.getLastRow(); // get the last row with data in the sheet
```

**Comment by lbyzx123** [comment]
Great! Thanks! I'm looking forward to your solution.

**Comment by miachm** [comment]
A workaround was made for this issue. Now it can open/save this file.
Try the new version v1.2.0

**Comment by lbyzx123** [comment]
version : 1.2.1
When reading a simple ODS file, there is no problem. but when reading the ODS file edited by Office 2010, the following error occurs:
"C:\Program Files\Java\jdk1.8.0_05\bin\java" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.2\lib\idea_rt.jar=50223:C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_05\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_05\jre\lib\rt.jar;D:\eclipse4.11\workspace\OdsTest\target\classes;F:\maven-local-repository\com\github\miachm\sods\SODS\1.2.1\SODS-1.2.1.jar" com.hikvision.test.ODSParserHelper
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.github.miachm.sods.Sheet.checkLazyRowLoading(Sheet.java:306)
	at com.github.miachm.sods.Sheet.getCell(Sheet.java:296)
	at com.github.miachm.sods.Range.iterateRange(Range.java:624)
	at com.github.miachm.sods.Range.setStyle(Range.java:718)
	at com.github.miachm.sods.OdsReader.processCells(OdsReader.java:413)
	at com.github.miachm.sods.OdsReader.processTable(OdsReader.java:279)
	at com.github.miachm.sods.OdsReader.processSpreadsheet(OdsReader.java:223)
	at com.github.miachm.sods.OdsReader.iterateFilesEntries(OdsReader.java:216)
	at com.github.miachm.sods.OdsReader.processContent(OdsReader.java:77)
	at com.github.miachm.sods.OdsReader.load(OdsReader.java:43)
	at com.github.miachm.sods.OdsReader.load(OdsReader.java:35)
	at com.github.miachm.sods.SpreadSheet.<init>(SpreadSheet.java:52)
	at com.github.miachm.sods.SpreadSheet.<init>(SpreadSheet.java:39)
	
	
My file download link is: https://github.com/lbyzx123/SODS/blob/master/oak.ods

When reading files, the CPU takes up 90%.Can you help me see where the problem is?Thank you very much.

**Comment by miachm** [comment]
The reason is, it tries to create all the columns/rows declared by excel. That takes memory and cpu time. I am trying to avoid it when these columns/rows are not being used (like now).

I uploaded a provisional version (1.2.2-SNAPSHOT) in maven. Can you try it?

**Comment by lbyzx123** [comment]
> The reason is, it tries to create all the columns/rows declared by excel. That takes memory and cpu time. I am trying to avoid it when these columns/rows are not being used (like now).
> 
> I uploaded a provisional version (1.2.2-SNAPSHOT) in maven. Can you try it?

Thank you very mach.I will try it

**Comment by lbyzx123** [comment]
I will try it.






At 2019-12-12 06:55:13, "Miguel Chacon" <notifications@github.com> wrote:


The reason is, it tries to create all the columns/rows declared by excel. That takes memory and cpu time. I am trying to avoid it when these columns/rows are not being used (like now).

I uploaded a provisional version (1.2.2-SNAPSHOT) in maven. Can you try it?

**Comment by lbyzx123** [comment]
How do I get version 1.2.2-snapshot.

**Comment by miachm** [comment]
[SODS-1.2.2-SNAPSHOT.jar.zip](https://github.com/miachm/SODS/files/3958126/SODS-1.2.2-SNAPSHOT.jar.zip)

**Comment by lbyzx123** [comment]
It works very well in my application.Thanks you very much.
