### ISSUE TITLE
Possible error when reading the font size

### ISSUE THREAD

**Issue by HectorLPA** [miachm/SODS#21]
Hi, reading an ods file I have encountered a possible error reading the fontsize, it expects an int value and it is arriving a decimal one. The class is OdsReader.java line 147

![issueDetected](https://user-images.githubusercontent.com/5472628/83245103-3258c200-a198-11ea-85f6-fff6a7d8aedc.png)

**Comment by HectorLPA** [comment]
Hi again, with this change it reads the ods file perfectly.
![fixError](https://user-images.githubusercontent.com/5472628/83266833-46fa8180-a1bb-11ea-91f8-9edfb9249f61.PNG)

greetings

**Comment by miachm** [comment]
Thanks for you report!

Noted, it will be included to the next release :)

**Comment by HectorLPA** [comment]
Nice, thanks!

Muchas gracias ;)

**Comment by miachm** [comment]
Solved in v1.3.0
