### ISSUE TITLE
Possible error when reading cells with comments

### ISSUE THREAD

**Issue by HectorLPA** [miachm/SODS#22]
Hi again, when reading a cell which has comments, when reading the cell value it concatenates the cell's value with the comment. Is this an error? 

![CapturaODS](https://user-images.githubusercontent.com/5472628/84261998-b6099b80-ab14-11ea-98df-32bc914c1e07.png)

![CapturaODS_2](https://user-images.githubusercontent.com/5472628/84262059-d3d70080-ab14-11ea-84c9-334c9530ec3e.png)

Thanks in advance

Greetings

**Comment by miachm** [comment]
Solved in v1.3.0
