### ISSUE TITLE
Wrong detection empty cells 

### ISSUE THREAD

**Issue by fnasibov** [miachm/SODS#23]
Hi, bug with [file](https://yadi.sk/i/QypvYRPEvD06UQ).
When i creating SpreadSheet from this file. It creates million cells and styles in it. Because detecting empty cells is incorrect.
this is loadded spreadSheet in debugger. Attention to dimension.
![image](https://user-images.githubusercontent.com/39213506/87020342-bf098d80-c1e4-11ea-8804-5f5d9b01f00e.png)
And this is memory snapshot screenshot in visualVM 
![image](https://user-images.githubusercontent.com/39213506/87020589-1ad41680-c1e5-11ea-9b11-13f2ece43f0e.png)
Will be nice if answer me.

**Comment by miachm** [comment]
The number 1048576 is a bug with ODS files generated by Microsoft Excel (#12 ). But it was already solved in v1.2.2. I tried your file in the release and it works like expected

May I know which version are you using?

**Comment by fnasibov** [comment]
Thank you for response. i used v1.2.1. I should update it!)

**Comment by miachm** [comment]
Perfect then :)
