### ISSUE TITLE
nên bổ sung thêm Font cho ô tính, bảo vệ trang tính, bảo vệ ô tính

### ISSUE THREAD

**Issue by quynlc** [miachm/SODS#30]
Tôi rất thích thư viện SODS (link: https://github.com/miachm/SODS) để đọc/ghi tệp ods. Tuy nhiên, tôi không tìm thấy thấy định dạng font chữ. Ví dụ: sheet.getRange(2,2).setFontName("Times New Roman");
và tôi muốn đặt mật khẩu bảo vệ sheet, bảo vệ ô tính, ví dụ:
 sheet.setPassWord("PassWord"); hoặc sheet.setPassWord(""); //Mật khẩu bảo vệ sheet
 sheet.getRange(2,2).setProtected(true); //Bảo vệ ô tính
Rất mong bạn sớm code bổ sung.
Xin cảm ơn!

**Comment by miachm** [comment]
Hi Quynlc!

Do you speak English? I don´t speak your language

Thanks,
Miguel

**Comment by quynlc** [comment]
a function should be added to password protect the sheet

**Comment by miachm** [comment]
Implemented in v1.4.0
