### ISSUE TITLE
Range.getValue() returns LocalDate instead of Date

### ISSUE THREAD

**Issue by mmitch** [miachm/SODS#54]
The JavaDoc for `Range.getValue()` says
```
Returns the value of the top-left cell in the range.
The values could be String, Float, Integer, OfficeCurrency, OfficePercentage or a Date
Empty cells returns a null object
```

On my first try of SODS (version 1.5.2), reading a cell with a date gave me a `java.time.LocalDate` instead of a `Date`.

I like this because I want a LocalDate and don't have to write a conversion Date->LocalDate, but the documentation is a bit off.

Is the resulting type depending on the cell formatting?   I have explicitely set the cell format to `tt.mm.jjjj` (like `yyyy-mm-dd` but for German locale) in the spreadsheet.

**Comment by miachm** [comment]
Javadoc updated
