### ISSUE TITLE
Currency fields don't seem to work (format and larger values)

### ISSUE THREAD

**Issue by sdaschner** [miachm/SODS#57]
The formatting with currency fields don't seem to be displayed. I've tried the code in your `ValueTypeTest.java` and the resulting Spreadsheet is not formatted, it just displays `-5`. Also the values seem to be cut weirdly if they are greater than 999, e.g. try the following:

```java
OfficeCurrency canada = new OfficeCurrency(Currency.getInstance(Locale.CANADA), -3050.5d);
OfficeCurrency eur = new OfficeCurrency(Currency.getInstance("EUR"), -2567.5d);
Sheet sheet = new Sheet("A", 1, 2);

sheet.getDataRange().setValues(canada, eur);
// ...
```

This results in a sheet displaying `-3` and `-2` for me...

**Comment by miachm** [comment]
Fixed in v1.5.3
