### ISSUE TITLE
Leading space

### ISSUE THREAD

**Issue by AdamKuzminski** [miachm/SODS#6]
It seems that for cells with text with leading space (or spaces) the lib returns null value.
Example:
<table:table-cell office:value-type="string" calcext:value-type="string"><text:p><text:s/>Test </text:p></table:table-cell>
Value of that cell is null.

**Comment by miachm** [comment]
Thanks for the report!

I see the problem, the tag [<text:s>](http://docs.oasis-open.org/office/v1.2/cs01/OpenDocument-v1.2-cs01-part1.html#__RefHeading__1415202_253892949) is not implemented. It shouldn't be hard to fix...

**Comment by miachm** [comment]
Solved and released!
