### ISSUE TITLE
Rename sheet name

### ISSUE THREAD

**Issue by prisme60** [miachm/SODS#84]
I am using a template file for my application with a default sheet name. I need to rename the sheet name when I write my new file. So I have added a `setName` method in the Sheet class.

```java
    /**
     * Rename this sheet
     * @param newName The new name of the sheet
     */
    public void setName(String newName) {
        this.name = newName;
    }
```

Is it possible to add this method ?

Thank you in advance.

**Comment by miachm** [comment]
I can't believe that this method doesn't exist Oo

Yes of course

**Comment by prisme60** [comment]
Thank you for your really fast answer ! I see that you already commit it ([3a45a31](https://github.com/miachm/SODS/commit/3a45a313ec974da1bf0b67393f6a7d0280cf71ca)) 👍
