### ISSUE TITLE
Issues when opened in Microsoft Excel

### ISSUE THREAD

**Issue by MinMatth-Magi** [miachm/SODS#85]
This issue is related to [this discussion](https://github.com/miachm/SODS/discussions/82).

Many incoherences remain when the _.ods_ files generated with SODS are opened in Microsoft Excel.

I'll focus my example on 3 columns of the following generated file: [sodsExample.ods](https://github.com/miachm/SODS/files/13662841/sodsExample.ods)

Here, the file is opened in LibreOffice:
![image](https://github.com/miachm/SODS/assets/44207159/5ff5b511-ceec-4fa8-9ed2-28ceeae16bb4)

And here how it looks in Excel (without any edit, it is the exact same file):
![image](https://github.com/miachm/SODS/assets/44207159/c0c666cf-cbf4-4ca4-aea4-74723851197b)

We can notice that some cells don't keep their original value once opened in Excel, and they can even be duplicated. I have no idea why to be honest :/ Hopefully, you might !

Please tell me if you need anything more,
Matthieu

**Comment by miachm** [comment]
Could you edit the file in Excel (so it's shown as expected). Save it and send the file back to me?

Need to see what Excel is expecting.

**Comment by MinMatth-Magi** [comment]
Okay! Here are some files generated in different situations:

- Created from scratch in Microsoft Excel, setting the correct data manually, saved into a [.xlsx file](https://github.com/miachm/SODS/files/13671007/Book.xlsx) and a [.ods file](https://github.com/miachm/SODS/files/13671006/Book.ods).
- The generated file saved into a [.ods file](https://github.com/miachm/SODS/files/13671040/sodsExample_savedWithoutEditAfterOpened.ods) (I couldn't save it as a .xlsx file, but saving it back as a .ods file kept the errors showing up in Microsoft Excel in the .ods file too).
- The generated file saved into a [.ods file](https://github.com/miachm/SODS/files/13671408/sodsExample_savedAfterSettingTheDataManually.ods) after setting the correctly again.

All those files have been manipulated/saved in Microsoft Excel directly. But sadly it seems that I cannot save a .ods file, opened in Microsoft Excel, as a .xlsx file.

**Comment by miachm** [comment]
Dam, I can't see a thing. I don't understand why Excel doesn't like it.

**Comment by MinMatth-Magi** [comment]
Excel is mean ! 😞

Do you think you will still be able to look into it or will it be a dead end ?

For sure, there are some differences between the [generated file](https://github.com/miachm/SODS/files/13662841/sodsExample.ods) and the [manually fixed ods file](https://github.com/miachm/SODS/files/13671408/sodsExample_savedAfterSettingTheDataManually.ods) that I saved from Excel. 🤔

**Comment by miachm** [comment]
Of course there is a solution. But it's not that trivial like expected.

What I usually do is to rename the .ods to .zip. Then I extract the file and I check the XML tags for content.xml.

SODS XML tags are correct according the standard, that's why you can open it in Libre Office. But Excel doesn't follow the standard, it is expecting additional tags which are not documented.

The question is. Which tag?

**Comment by miachm** [comment]
This was tricky, but I managed to test it in the Excel Online. It should have the same behaviour for the desktop Excel (well, I hope :))

**Comment by miachm** [comment]
Sorry for the delay. It should be fixed now in 1.6.7

**Comment by MinMatth-Magi** [comment]
That did the trick ! Thank you ! 😄
I'm closing the issue now.

Little detail I noticed: the '\n' doesn't seem to work in Microsoft Excel while it does in LibreOffice. But it's not much of an annoyance for me personally 😉
