### ISSUE TITLE
missing data for consequent duplicite lines

### ISSUE THREAD

**Issue by antonsjava** [miachm/SODS#86]
[oo-ods-test.zip](https://github.com/miachm/SODS/files/13714783/oo-ods-test.zip)
Hello 

I just try sods for first time and it seems there is bug (maybe I don't understant it)

I try to make scenario where create and read ods file line by line.

sk.antons.sods.CreateDoc
 - reads ./src/data/duplicate-lines.csv 
 - copy content of csv to ./target/sods.ods

sk.antons.sods.ReadDoc
 - reads ./target/sods.ods
 - copy content to ./target/sods-output-copied.csv 
 - copy content to ./target/sods-output2-copied.csv  (just other way of sods use)

scenario 1 
 - start CreateDoc
 - start ReadDoc  
 - when I open ./target/sods.ods in libreoffice it seems ok 
 - when you look to ./target/sods-output-copied.csv or ./target/sods-output-copied2.csv data of duplicate consequent lines are mising (only lastone is present)

scenario 2 
 - start CreateDoc
 - open ./target/sods.ods in libreoffice and save it  
 - start ReadDoc  
 - when I open ./target/sods.ods in libreoffice it seems ok 
 - when you look to ./target/sods-output-copied.csv or ./target/sods-output-copied.csv all data are present

So it seems that created ods file is somehow wrong for consequent reading by sods.

Thanks

**Comment by antonsjava** [comment]
in attached file there are all generated files together with code so you can recreate them if you want

**Comment by miachm** [comment]
> when you look to ./target/sods-output-copied.csv or ./target/sods-output-copied2.csv data of duplicate consequent lines are mising (only lastone is present)

I... Don't understand this line. You mean is missing data?

**Comment by antonsjava** [comment]
when you look at generated file ./target/sods-output-copied.csv or ./target/sods-output2-copied.csv 

if you look on line 11 for example it looks like 

;;;;;;;;

but it should be 

3;3;3;;;;;;

data are mising

if you have 'same lines' in generated ods they are unable to read (until you explicitly save that ods file in office application)
only last line for each serie of same lines are present
(look to ./src/data/duplicate-lines.csv - result should look same - plus/minus of empty cells)

**Comment by miachm** [comment]
Okay found it. The interpretation of the tag "table:number-rows-repeated" is buggy in its reading implementation. It's not applying the value to the repeated rows.

LibreOffice is not using that tag in their files (at least in the example you gave me). That's why re-saving the file worked.

**Comment by miachm** [comment]
Fixed in the last commit

**Comment by miachm** [comment]
Released into 1.6.7
